on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * *'
    # This runs at 10:00 AM UTC each day.
    # * is a special character in YAML so you have to quote this string

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: install python packages
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            beautifulsoup4==4.12.3
            bs4==0.0.2
            Markdown==3.7
            soupsieve==2.6
            
      - name: run python script
        run: python3 scripts/create-software.py
      # Commit and push
      - name: GIT commit and push docs overriding conflicts with local changes (verbose)
        env: 
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "youp_hendriks@hotmail.com"
          git add db/*
          git add pages/*
          git add index.html
          git commit -m "Pushed using Github Actions"
          git push
    
    
   
